blank_issues_enabled: true
contact_links:
  - name: Help
    url: https://discord.com/invite/lychee
    about: Please join our Discord server for help using Lychee
  - name: Troubleshooting
    url: https://github.com/lychee/lychee/blob/main/docs/faq.md#faq
    about: See the FAQ for common issues and solutions
